name: supabase_native_auth
description: Package that adds native sign in for your Supabase app.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.0
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  # supabase_flutter: ^1.10.4
  supabase_flutter:
    path: ../supabase_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
